repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint


  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.21
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black

  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.0
    hooks:
      - id: fmt
      - id: test
